### ISSUE TITLE
Drop happyplan

### ISSUE THREAD

**Issue by MoOx** [MoOx/moox.io#66]
http://www.metalsmith.io/

**Comment by ismay** [comment]
If you're switching to metalsmith you might like (parts of) [my setup](https://github.com/ismay/ismaywolff.nl). Or not :)

**Comment by MoOx** [comment]
Thanks for sharing that, but I am having fun with a new engine https://github.com/MoOx/statinamic

**Comment by ismay** [comment]
Ah that looks cool too. Been thinking about using react myself as well!
